<?php

namespace A21\LexiconClient\Support;

use RuntimeException;

class LexiconConfigGuard
{
    /**
     * @param  array<string, mixed>  $config
     * @return list<string>
     */
    public static function missingKeys(array $config): array
    {
        $missing = [];

        foreach ([
            'api_url' => 'LEXICON_API_URL',
            'client_code' => 'LEXICON_CLIENT_CODE',
            'project_code' => 'LEXICON_PROJECT_CODE',
            'secret' => 'LEXICON_CLIENT_SECRET',
        ] as $key => $env) {
            $value = $config[$key] ?? null;

            if (! is_string($value) || trim($value) === '') {
                $missing[] = $env;
            }
        }

        return $missing;
    }

    /**
     * Refuse to run Lexicon client actions without a configured project secret.
     * The secret must come from the Lexicon integration client and be set in the
     * project .env — it is never generated by these commands.
     *
     * @param  array<string, mixed>  $config
     */
    public static function assertReady(array $config): void
    {
        $missing = self::missingKeys($config);

        if ($missing === []) {
            return;
        }

        throw new RuntimeException(
            'Lexicon is not configured for this project. Missing: '.implode(', ', $missing).'. '
            .'Set these in the project .env (create the secret in Lexicon → Integration Clients; do not auto-generate it here).'
        );
    }
}
